version: '3.1'
services:
    jenkins:
      build:
        context: .

          image: jenkins-container:v0.1
          ports:
            - 8000:8080
            - 50000:50000
          volumes:
          - "jenkins-data:/var/jenkins_home"

volumes:
    jenkins-data:
