name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.senhadecente.com.br/jenkins/jenkins:$(date +%s)
    - name: Push image to registry
      uses: mr-smithers-excellent/docker-build-push@v5    
      with:
        image: reg.senhadecente.com.br/jenkins
        tags: v1, latest
        registry: reg.senhadecente.com.br
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
