name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.senhadecente.com.br/senhadecente.com.br/jenkins:$(date +%s)
    - name: Push to repo
      run: echo -n ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin reg.senhadecente.com.br | docker push reg.senhadecente.com.br/senhadecente.com.br/jenkins:$(date +%s)
